site_name: Android Interview Prep
site_url: https://tauqir295.github.io/android-interview-prep/
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences